import { ENUM_PLAN_BILLING_CYCLE, ENUM_PLAN_TYPE, PlanType } from "@/types/plan"

export const staticPlans: PlanType[] = [
  {
    id: 5,
    amount: 10000,
    discount: 0,
    duration: ENUM_PLAN_BILLING_CYCLE.MONTHLY,
    plan_type: ENUM_PLAN_TYPE.INDIVIDUAL,
    subscription_benefits: [
      { id: 32, benefit: "Access for 1 child" },
      { id: 34, benefit: "Personal Student Dashboard" },
      { id: 33, benefit: "Verified Completion Certificate" },
      { id: 35, benefit: "Full AI Curriculum" },
      { id: 31, benefit: "Monthly Progress Reports" },
    ],
  },
  {
    id: 6,
    amount: 27000,
    discount: 0,
    duration: ENUM_PLAN_BILLING_CYCLE.QUARTERLY,
    plan_type: ENUM_PLAN_TYPE.INDIVIDUAL,
    subscription_benefits: [
      { id: 42, benefit: "Access for 1 child" },
      { id: 44, benefit: "Personal Student Dashboard" },
      { id: 41, benefit: "Quarterly Progress Reports" },
      { id: 45, benefit: "Full AI Curriculum" },
      { id: 43, benefit: "Verified Completion Certificate" },
    ],
  },
  {
    id: 7,
    amount: 100000,
    discount: 0,
    duration: ENUM_PLAN_BILLING_CYCLE.YEARLY,
    plan_type: ENUM_PLAN_TYPE.INDIVIDUAL,
    subscription_benefits: [
      { id: 48, benefit: "Full AI Curriculum" },
      { id: 46, benefit: "Access for 1 child" },
      { id: 50, benefit: "Personal Student Dashboard" },
      { id: 49, benefit: "Yearly Progress Reports" },
      { id: 47, benefit: "Verified Completion Certificate" },
    ],
  },
  {
    id: 8,
    amount: 10000,
    discount: 0,
    duration: ENUM_PLAN_BILLING_CYCLE.MONTHLY,
    plan_type: ENUM_PLAN_TYPE.FAMILY,
    subscription_benefits: [
      { id: 52, benefit: "Access for up to 3 children" },
      { id: 51, benefit: "Shared Parent Control Dashboard" },
      { id: 55, benefit: "Priority Support & Feedback" },
      { id: 54, benefit: "Exclusive AI Scholar Badge" },
      { id: 53, benefit: "Full AI Curriculum" },
    ],
  },
  {
    id: 9,
    amount: 27000,
    discount: 0,
    duration: ENUM_PLAN_BILLING_CYCLE.QUARTERLY,
    plan_type: ENUM_PLAN_TYPE.FAMILY,
    subscription_benefits: [
      { id: 57, benefit: "Access for up to 3 children" },
      { id: 60, benefit: "Quarterly Progress Reports" },
      { id: 59, benefit: "Exclusive AI Scholar Badge" },
      { id: 56, benefit: "Shared Parent Control Dashboard" },
      { id: 58, benefit: "Full AI Curriculum" },
    ],
  },
  {
    id: 10,
    amount: 100000,
    discount: 0,
    duration: ENUM_PLAN_BILLING_CYCLE.YEARLY,
    plan_type: ENUM_PLAN_TYPE.FAMILY,
    subscription_benefits: [
      { id: 64, benefit: "Exclusive AI Scholar Badge" },
      { id: 61, benefit: "Shared Parent Control Dashboard" },
      { id: 62, benefit: "Access for up to 3 children" },
      { id: 63, benefit: "Full AI Curriculum" },
      { id: 65, benefit: "Priority Support & Feedback" },
    ],
  },
]
